teams: ['cvhunter1', 'cvhunter2','cvhunter3', 'cvhunter4',
        'visione1','visione2','visione3','visione4',
        'vibro1','vibro2','vibro3','vibro4']

audits_file: data/vbse2022/audits.jsonl
run_file: data/vbse2022/run.json

logs:
  cvhunter1: data/vbse2022/team_logs/CVHunter1/resultlogs
  cvhunter2: data/vbse2022/team_logs/CVHunter2/resultlogs
  cvhunter3: data/vbse2022/team_logs/CVHunter3/resultlogs
  cvhunter4: data/vbse2022/team_logs/CVHunter4/resultlogs
  visione1: data/vbse2022/team_logs/visione1
  visione2: data/vbse2022/team_logs/visione2
  visione3: data/vbse2022/team_logs/visione3
  visione4: data/vbse2022/team_logs/visione4
  vibro1: data/vbse2022/team_logs/vibro1
  vibro2: data/vbse2022/team_logs/vibro2
  vibro3: data/vbse2022/team_logs/vibro3
  vibro4: data/vbse2022/team_logs/vibro4

generate:
  - name: time_recall_table_vbse2022
    function: generate.TimeRecallTableVbse2022
    generate_args: {split_user: False, only_best_user: False, max_records: 10000}
    render_args: {}

