teams: ['HTW', 'VISIONE', 'VIREO', 'vitrivr-VR', 'vitrivr', 'Verge', 'VideoCLIP'] #, 'FIRST']

audits_file: data/2023/vbs23_audits.jsonl
run_file: data/2023/vbs23_run.json
fps_files: 
 - data/v3c1_2_fps.csv
 - data/mvk_fps.csv
segment_files:
 - data/v3c1_frame_segments.csv
 - data/v3c2_frame_segments.csv
 - data/mvk_frame_segments.csv

logs:
  VISIONE: data/2023/team_logs/VISIONE # data/2023/team_logs/from_dres/visione
  vitrivr: data/2023/team_logs/from_dres/vitrivr
  VideoCLIP: data/2023/team_logs/from_dres/videoclip
  Verge: data/2023/team_logs/from_dres/verge
  VIREO: data/2023/team_logs/VIREO
  HTW: data/2023/team_logs/vibro
  FIRST: data/2023/team_logs/FIRST