teams: ['VISIONE']

logs:
  VISIONE: team_logs/logs_VISIONE/DRES_log
  vireo: team_logs/vibro
  diveXplore: team_logs/divexplore_logs"

generate:
  - name: time_recall_table
    function: generate.TimeRecallTable
    generate_args: {}
    render_args: {}

  - name: best_shot_rank_boxplot
    function: generate.BestShotRankBoxplot
    generate_args: {}
    render_args: {}
