teams: ['VideoCLIP'] # ['VISIONE', 'videoclip', 'VERGE']

audits_file: data/2023/vbs23_audits.jsonl
run_file: data/2023/vbs23_run.json
fps_files: 
 - data/v3c1_2_fps.csv
 - data/mvk_fps.csv
segment_files:
 - data/v3c1_frame_segments.csv
 - data/v3c2_frame_segments.csv
 - data/mvk_fps.csv

logs:
  VISIONE: data/2023/team_logs/VISIONE # data/2023/team_logs/from_dres/visione
  vitrivr: data/2023/team_logs/from_dres/vitrivr
  VideoCLIP: data/2023/team_logs/from_dres/videoclip
  VERGE: data/2022/team_logs/from_dres/verge