teams: ['visione']

generate:
  function: generate.BestShotRankBoxplot
  cache_team_logs: True # TODO: to be implemented

  args:
    cache: True
    cache_path: cache
    cache_filename: TimeRecallTable.pkl # shares the same precomputation from the time_recall_table plot