teams: ['visione', 'viret']

generate:
  function: generate.TimeRecallTable
  # cache_team_logs: True # TODO: to be implemented

  args:
    cache: True       # TODO: move into args
    cache_path: cache


# TODO: single configuration file, is easier